### PR TITLE
Add installation notes for self-updating `sl`.

### PR DESCRIPTION
**Pull request by Ferada**

### CODE REVIEW

**Comment by vlad-alexandru-ionescu** [comment]
I'm thinking we should only have the wrapper and nothing else. Any reason why we shouldn't do that?

**Comment by Ferada** [comment]
> I'm thinking we should only have the wrapper and nothing else. Any reason why we shouldn't do that?

Not really. That reminds me, I could also mention there that `SHIFTLEFT_NO_AUTO_UPDATE` will inhibit auto-updating ... if for some reason a customer would feel uncomfortable with it doing that? That was at least one reason for adding it.

**Comment by vlad-alexandru-ionescu** [comment]
Sounds good - let's make this the only documented option.

**Comment by Ferada** [comment]
Updated.

**Comment by vlad-alexandru-ionescu** [comment]
cc @NWeber-SL @arunmecheri

**Comment by vlad-alexandru-ionescu** [comment]
Hey Olof, changes were made to a duplicate file that was not in use. Nancy will delete the duplicate and port over your changes to the right file.

**Pull request closed without merging**
